# Generated by Django 6.0.2 on 2026-02-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text="FontAwesome icon class (e.g., 'fas fa-user-graduate')", max_length=100)),
                ('value', models.CharField(help_text="The number or text to display (e.g., '40+')", max_length=50)),
                ('label', models.CharField(help_text="The label below the number (e.g., 'Active Researchers')", max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Controls the display order (lower numbers appear first)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
