# Generated by Django 6.0.2 on 2026-02-19 20:27

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_progressstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='image')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('authors', models.CharField(blank=True, max_length=300, null=True)),
                ('paper_link', models.URLField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('pub_type', models.CharField(choices=[('Conference', 'Conference'), ('Journal', 'Journal'), ('Preprint', 'Preprint'), ('Workshop', 'Workshop')], default='Conference', max_length=50)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Under Review', 'Under Review'), ('Upcoming', 'Upcoming'), ('Published', 'Published'), ('Accepted with minor revision', 'Accepted with minor revision')], default='Published', max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in the Featured Publications section')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
