# Generated by Django 6.0.2 on 2026-02-19 20:58

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='image')),
                ('name', models.CharField(max_length=200)),
                ('lab_designation', models.CharField(choices=[('Advisor', 'Advisory Panel'), ('PI', 'Principal Investigator'), ('Investigator', 'Investigator'), ('Mentor', 'Research Mentor'), ('RA', 'Research Assistant'), ('URA', 'Undergraduate Research Assistant')], max_length=50)),
                ('self_designation', models.CharField(help_text='e.g., Professor of CSE, Data Scientist', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
