# Generated by Django 6.0.2 on 2026-02-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_reply', models.TextField(blank=True, help_text="Write your reply here and click 'Save'. An email will be sent directly to the user.", null=True)),
                ('is_replied', models.BooleanField(default=False, help_text='Automatically checked when a reply is sent.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='contact@dipanchallab.org', max_length=254)),
                ('phone', models.CharField(default='+880 1234-567890', max_length=20)),
                ('address', models.TextField(default='Sylhet, Bangladesh')),
                ('office_hours', models.CharField(default='Mon-Fri, 9:00 AM - 5:00 PM (Asia/Dhaka)', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Lab Information',
            },
        ),
    ]
