# Generated by Django 6.0.2 on 2026-02-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactmessage_labinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='labinformation',
            name='description',
            field=models.TextField(default='Dipanchal Innovation Lab (DiL) is dedicated to pioneering research in AI, fostering technological growth, and delivering innovation for humanity.'),
        ),
        migrations.AddField(
            model_name='labinformation',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labinformation',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labinformation',
            name='orcid',
            field=models.URLField(blank=True, help_text="Link to the lab's or lead PI's ORCID profile", null=True),
        ),
    ]
